return {
    [[English]],
    ParticipatoryStatistic = "{1} | Amount:{2}/{3} | Remaining:{4} | Percentage:{5}% ({6} {7}/{8})",
    PromptJoinFaction = "Which faction would you like to join?",
    PromptAssignJob = "Please choose your job. (Remaining life: {1})",
    PromptChooseGear = "Please select a set of initial gear.",
    PrivateJoinFactionSuccess = "You have joined \"{1}\" faction.",
    BoardcastTeammateJoinFactionSuccess = "{1} joined your faction.",
    PrivateJoinFactionFailure = "You are temporarily unable to join \"{1}\" faction, possibly because 1) The number of people joining the Faction has reached its maximum, 2) The number of people exceeds the ratio, or 3) the number of entry tickets is insufficient.",
    JobLiveConsumption = "Consumption: {1} life",
    PrivateAssignJobSuccess = "Your job has been assigned as \"{1}\".",
    BoardcastTeammateAssignJobSuccess = "{1}'s job has been assigned as \"{2}\".",
    PrivateAssignJobFailure = "Your job cannot be assigned as \"{1}\" temporarily, possibly because 1) The number of people with the Job has reached its maximum, 2) The number of people exceeds the ratio, 3) the number of entry tickets is insufficient, or 4) your remaining life is insufficient, 5) temporarily unable to assign the job or even any jobs that belonged to the faction you joined.",
    PrivateChooseGearSuccess = "Your initial gear is \"{1}\".",
    BoardcastTeammateChooseGearSuccess = "{1}'s initial gear is \"{2}\".",
    PrivateChooseGearFailure = "You are temporarily unable to choose \"{1}\" as your initial gear, possibly because 1) The number of people who choose this gear has reached its maximum, 2) The number of people exceeds the ratio, or 3) The number of entry tickets is insufficient. 4) temporarily not allow to spawn the specified gear belonged to the assigned job.",
    ChatCommandFixPrompt = "Fix that you cannot choose factions, jobs, and gears due to dialog box not popping up",
    ChatCommandFactionList = "Get faction list",
    ChatCommandJoinFaction = "Assign specified faction",
    ChatCommandJobList = "Get job list",
    ChatCommandAssignJob = "Assign specified job",
    ChatCommandAssignJobs = "Assign all jobs",
    ChatCommandGearList = "Get gear list",
    ChatCommandSpawnGear = "Spawn specified gear",
    ChatCommandSpawnGears = "Spawn all gears"
}
