return {
    [[Simplified Chinese]],
    Unknown = "未知的",
    ParticipatoryStatistic = "{1} | 量:{2}/{3} | 剩:{4} | 率:{5}% ({6} {7}/{8})",
    PromptJoinFaction = "请问您想加入哪方派系？",
    PromptAssignJob = "请选择你意愿的职业。(剩余生命：{1})",
    PromptChooseGear = "请你选择一套初始装备。",
    PrivateJoinFactionSuccess = "你加入了“{1}”派系。",
    BoardcastTeammateJoinFactionSuccess = "{1}加入了派系“{2}”。",
    PrivateJoinFactionFailure = "你暂时无法加入“{1}”派系，原因可能是1)该阵营的人数已满，2)超出了人数比例，3)入场券数量不够。",
    JobLiveConsumption = "消耗：{1} 生命",
    PrivateAssignJobSuccess = "你的职业被分配为“{1}”。",
    BoardcastTeammateAssignJobSuccess = "{1}的职业被分配为“{2}”。",
    PrivateAssignJobFailure = "你的职业暂时无法被分配为“{1}”，原因可能是1)该职业人数已达上限，2)超出了人数比例，3)入场券数量不够，4)你所剩生命不足，5）所属阵营目前暂时还无法发配该职业或甚至是任何职业。",
    PrivateChooseGearSuccess = "你的初始装备是“{1}”。",
    BoardcastTeammateChooseGearSuccess = "{1}的初始装备是“{2}”。",
    PrivateChooseGearFailure = "你暂时无法选择“{1}”作为初始装备，原因可能是1)选择该出装的人数已达上限，2)超出了人数比例，3)入场券数量不够，4）所属职业目前暂时还无法发配该装备。",
    ChatCommandFixPrompt = "修复因对话框没有显示而导致无法选择派系、职业、出装的问题",
    ChatCommandFactionList = "获取派系列表",
    ChatCommandJoinFaction = "分配指定派系",
    ChatCommandJobList = "获取职业列表",
    ChatCommandAssignJob = "分配指定职业",
    ChatCommandAssignJobs = "分配所有职业",
    ChatCommandGearList = "获取装备列表",
    ChatCommandSpawnGear = "生成指定装备",
    ChatCommandSpawnGears = "生成所有装备",
}
